### ISSUE TITLE
Unable to use 1.3.1

### ISSUE THREAD

**Issue by JonathanWMorris** [homebridge/homebridge#2838]
**Describe The Bug:**

After updating home bridge to 1.3.1, I was stuck on a boot loop with an error saying the following. Rolling back to 1.3.0 fixes this issue.

**To Reproduce:**

All I did was update home bridge through the HomeBridge UI.

**Expected behavior:**

I expected Home bridge to successfully boot up and start running again.

[**Logs:**]()

```
Secondary Homebridge Logs here
```[2/23/2021, 8:02:03 AM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[2/23/2021, 8:02:08 AM] [HB Supervisor] Restarting Homebridge...
[2/23/2021, 8:02:08 AM] [HB Supervisor] Starting Homebridge with extra flags: -I
[2/23/2021, 8:02:08 AM] [HB Supervisor] Started Homebridge v1.3.1 with PID: 24829
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'source-map-support/register'
Require stack:
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/cli.js:24:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/homebridge/lib/cli.js',
    '/usr/local/lib/node_modules/homebridge/bin/homebridge'
  ]
}

**Homebridge Config:**
<!-- Paste relevant output between the two ``` lines below -->
<!-- Remove any sensitive information, passwords, etc. -->

```json
{
    "bridge": {
        "name": "Homebridge 8D83",
        "username": "0E:A9:DB:81:8D:83",
        "port": 51121,
        "pin": "***-**-***"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Nest",
            "googleAuth": {
                "issueToken": "token",
                "cookies": "cookies",
                "apiKey": "apiKey"
            },
            "options": [
                "Thermostat.SeparateBuiltInTemperatureSensor.Enable",
                "Thermostat.SeparateBuiltInHumiditySensor.Enable"
            ],
            "platform": "Nest"
        }
    ]
}
```

**Screenshots:**

**Environment:**

* **Node.js Version**:  v14.15.5
* **NPM Version**:  v6.14.11
* **Homebridge Version**:  1.3.1
* **Operating System**: macOS
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
Uninstall / reinstall.

```
npm uninstall -g homebridge

npm uninstall -g --unsafe-perm homebridge
```

If you encounter permission errors, add `sudo` to the command.

**Comment by JonathanWMorris** [comment]
> Uninstall / reinstall.
> 
> 
> 
> ```
> 
> npm uninstall -g homebridge
> 
> 
> 
> npm uninstall -g --unsafe-perm homebridge
> 
> ```
> 
> 
> 
> If you encounter permission errors, add `sudo` to the command.

Hi, 
Let me clarify, sorry but I think my title was misleading. I am able to update to 1.3.1 but after I do, home bridge doesn't work.

**Comment by oznu** [comment]
> Let me clarify, sorry but I think my title was misleading. I am able to update to 1.3.1 but after I do, home bridge doesn't work.

The logs suggest the upgrade did not complete successfully, the above commands should refresh the package.

**Comment by JonathanWMorris** [comment]
Thanks for your help! It worked when I uninstalled it and reinstalled it again.
