### ISSUE TITLE
TypeScript plugins do not build with noImplicitAny: true in 1.6.0

### ISSUE THREAD

**Issue by lstrojny** [homebridge/homebridge#3275]
### Analysis

Plugins that use TypeScript and are configured with `noImplicitAny: true` in `tsconfig.json` will fail the build with this error:

```
node_modules/hap-nodejs/dist/lib/Advertiser.d.ts:5:29 - error TS7016: Could not find a declaration file for module '@homebridge/dbus-native'. '(…)/node_modules/@homebridge/dbus-native/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/homebridge__dbus-native` if it exists or add a new declaration (.d.ts) file containing `declare module '@homebridge/dbus-native';`
```

The reason is that `Advertiser.ts` includes `InvokeError` from the `@homebridge/dbus-native` fork and that lacks type information.

A possible workaround is to define an ambient type in the plugin project like so:

```
declare module '@homebridge/dbus-native' {
    type InvokeError = unknown
}
```

See https://github.com/lstrojny/homebridge-prometheus-exporter/pull/42/commits/ab161aa4fd3ba49950e0d9a4cb59ec186719ee0d

It would probably be a good idea to change configure TypeScript in homebridge with `noImplicitAny` as well to catch accidental unsafe types.

### Expected Behavior

Projects should build

### Steps To Reproduce

1. Create a plugin with TypeScript
2. Set `noImplicitAny` to `true` in `tsconfig.json`
3. Run `tsc`

### Logs

```markdown
n.a.
```

### Configuration

```json
n.a.
```

### Environment

n.a.

### Process Supervisor

not applicable

**Comment by lstrojny** [comment]
Digging deeper, this is an issue in hap-nodejs, not in homebridge itself. hap-nodejs [defines ambient types for dbus-native](https://github.com/homebridge/HAP-NodeJS/blob/master/src/types/dbus-native.d.ts) already but it doesn’t export those. One possibility could be to submit the ambient types to https://github.com/DefinitelyTyped/DefinitelyTyped/

**Comment by hjdhjd** [comment]
This is a bug / regression to be sure. @Supereg - any direction on how you want to deal with this one?
