### ISSUE TITLE
Can't run after updating to 1.3.0

### ISSUE THREAD

**Issue by skiubek** [homebridge/homebridge#2831]
**Describe Your Problem:**

Hi. On previous version of Homebridge everything worked fine under Coreelec (Libreelec installation). After updating to 1.3.0 problem first appeared with Kodi plugin when i tried to update it. Thrown error was: " Cannot find module 'lru-cache' ". When I tried to uninstall it it was the same error. Now I tried to remove container Homebridge in docker, deleted folder with configuration (/storage/homebridge) and tried to reinstall it but the error is the same. It tries to do something but ends with a loop of the same error.
[**Logs:**]()

CoreELEC:~ # docker run -d --restart=always --net=host \
>   --name=homebridge \
>   -v /storage/homebridge:/homebridge \
>   -e HOMEBRIDGE_CONFIG_UI=1 \
>   -e HOMEBRIDGE_CONFIG_UI_PORT=8581 \
>   oznu/homebridge:aarch64
fa8993dc6bc2cb3e0dafa814043e0218fe1930a49fd43fed2adc77fe5d59c576
CoreELEC:~ # docker logs -f homebridge
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 
usermod: no changes
-------------------------------------
GID/UID
-------------------------------------
User uid:    911
User gid:    911
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-set-timezone: executing... 
Set system timezone to Europe/Warsaw.
[cont-init.d] 20-set-timezone: exited 0.
[cont-init.d] 30-packages: executing... 
[cont-init.d] 30-packages: exited 0.
[cont-init.d] 40-dbus-avahi: executing... 
mv: cannot remove '/etc/services.d/dbus': Invalid argument
mv: cannot remove '/etc/services.d/avahi': Invalid argument
[cont-init.d] 40-dbus-avahi: exited 1.
[cont-init.d] 45-user-data: executing... 
[cont-init.d] 45-user-data: exited 0.
[cont-init.d] 50-plugins: executing... 
    Thank you for using the oznu/homebridge docker image!
  If you find this project useful please STAR it on GitHub:
         https://github.com/oznu/docker-homebridge
                Or donate to the project:
            https://github.com/sponsors/oznu
                  https://paypal.me/oznu
Homebridge: Installing plugins...
internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module 'lru-cache'
Require stack:
- /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js
- /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/index.js
- /usr/local/lib/node_modules/npm/node_modules/libnpm/fetch.js
- /usr/local/lib/node_modules/npm/lib/utils/metrics.js
- /usr/local/lib/node_modules/npm/lib/npm.js
- /usr/local/lib/node_modules/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js',
    '/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/index.js',
    '/usr/local/lib/node_modules/npm/node_modules/libnpm/fetch.js',
    '/usr/local/lib/node_modules/npm/lib/utils/metrics.js',
    '/usr/local/lib/node_modules/npm/lib/npm.js',
    '/usr/local/lib/node_modules/npm/bin/npm-cli.js'
  ]
}
internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module 'lru-cache'
Require stack:
- /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js
- /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/index.js
- /usr/local/lib/node_modules/npm/node_modules/libnpm/fetch.js
- /usr/local/lib/node_modules/npm/lib/utils/metrics.js
- /usr/local/lib/node_modules/npm/lib/npm.js
- /usr/local/lib/node_modules/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js',
    '/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/index.js',
    '/usr/local/lib/node_modules/npm/node_modules/libnpm/fetch.js',
    '/usr/local/lib/node_modules/npm/lib/utils/metrics.js',
    '/usr/local/lib/node_modules/npm/lib/npm.js',
    '/usr/local/lib/node_modules/npm/bin/npm-cli.js'
  ]
}
[cont-init.d] 50-plugins: exited 0.
[cont-init.d] 55-config-ui: executing... 
Enabling homebridge-config-ui-x...
mv: cannot remove '/etc/services.d/homebridge': Invalid argument
[cont-init.d] 55-config-ui: exited 0.
[cont-init.d] done.
[services.d] starting services
s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise dbus: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise avahi: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise homebridge: warning: unable to spawn ./run - waiting 10 seconds
Starting cron
[services.d] done.
internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module 'lru-cache'
Require stack:
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/range.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/comparator.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/index.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/range.js:187:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/range.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/comparator.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/index.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js'
  ]
}
    Thank you for using the oznu/homebridge docker image!
  If you find this project useful please STAR it on GitHub:
         https://github.com/oznu/docker-homebridge
                Or donate to the project:
            https://github.com/sponsors/oznu
                  https://paypal.me/oznu
internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module 'lru-cache'
Require stack:
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/range.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/comparator.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/index.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/range.js:187:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/range.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/comparator.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/index.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js'
  ]
}
    Thank you for using the oznu/homebridge docker image!
  If you find this project useful please STAR it on GitHub:
         https://github.com/oznu/docker-homebridge
                Or donate to the project:
            https://github.com/sponsors/oznu
                  https://paypal.me/oznu
internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module 'lru-cache'
Require stack:
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/range.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/comparator.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/index.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/range.js:187:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/range.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/comparator.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/index.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js'
  ]
}
    Thank you for using the oznu/homebridge docker image!
  If you find this project useful please STAR it on GitHub:
         https://github.com/oznu/docker-homebridge
                Or donate to the project:
            https://github.com/sponsors/oznu
                  https://paypal.me/oznu
s6-supervise dbus: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise avahi: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise homebridge: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: No such file or directory
internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module 'lru-cache'
Require stack:
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/range.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/comparator.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/index.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/range.js:187:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/range.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/comparator.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/index.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js'
  ]
}
    Thank you for using the oznu/homebridge docker image!
  If you find this project useful please STAR it on GitHub:
         https://github.com/oznu/docker-homebridge
                Or donate to the project:
            https://github.com/sponsors/oznu
                  https://paypal.me/oznu
internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module 'lru-cache'
Require stack:
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/range.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/comparator.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/index.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/range.js:187:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/range.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/comparator.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/index.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js'
  ]
}
    Thank you for using the oznu/homebridge docker image!
  If you find this project useful please STAR it on GitHub:
         https://github.com/oznu/docker-homebridge
                Or donate to the project:
            https://github.com/sponsors/oznu
                  https://paypal.me/oznu
internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module 'lru-cache'
Require stack:
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/range.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/comparator.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/index.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/range.js:187:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/range.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/comparator.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/index.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js'
  ]
}
    Thank you for using the oznu/homebridge docker image!
  If you find this project useful please STAR it on GitHub:
         https://github.com/oznu/docker-homebridge
                Or donate to the project:
            https://github.com/sponsors/oznu
                  https://paypal.me/oznu
s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise dbus: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise avahi: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise homebridge: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: No such file or directory
internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module 'lru-cache'
Require stack:
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/range.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/comparator.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/index.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/range.js:187:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/range.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/comparator.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/index.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js'
  ]
}
    Thank you for using the oznu/homebridge docker image!
  If you find this project useful please STAR it on GitHub:
         https://github.com/oznu/docker-homebridge
                Or donate to the project:
            https://github.com/sponsors/oznu
                  https://paypal.me/oznu
```
Secondary Homebridge Logs here
```

**Homebridge Config:**

I have deleted folder /storage/homebridge, so i think there is nothing left.

```json
Show your homebridge config.json here
```
I have deleted folder /storage/homebridge, so i think there is nothing left.

**Screenshots:**

**Environment:**
Docker on Coreelec 9.2.5
* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 1.3.0
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other DOCKER
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by oznu** [comment]
Please pull down the latest Docker image and re-create the container.

**Comment by oznu** [comment]
Closing in favour of https://github.com/oznu/docker-homebridge/issues/353
